# Task 4.10 - Book 2.  Excluding low activity customers from the dataframe

## The Instacart CFO isn’t interested in customers who don’t generate much revenue for the app. Create an exclusion flag for low-activity customers (customers with less than 5 orders) and exclude them from the data. Make sure you export this sample.

##  The small_cop_sample dataframe sample of the Instacart dataframe will be used to identify active and low activity customers.

# This script contains the following points:

## 1. Import small_cop_sample dataframe

## 2. Create an exclusion flag

## 3. Exclude low activity customers from the dataframe

## 4. Export sample containing only active customers

In [1]:
# Import panda, numpy, os libraries

import pandas as pd
import numpy as np
import os

## 1. Import small dataframe

In [2]:
path = r'C:\Users\howl6\OneDrive\Certificates\CareerFoundry\Coursework\Data_Immersion\Chapter 4\Instacart Basket Analysis'

In [3]:
# Import small_cop_sample dataframe

df_cust = pd.read_pickle(os.path.join(path,'02_Data','Prepared_Data', 'small_cop_sample.pkl'))

In [4]:
df_cust.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_time_of_day,...,surname,gender,state,age,date_joined,num_of_dependants,family_status,income,_merge,region
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region
2,907,Premium Sliced Bacon,106,12,20.0,3160996,138,1,5,13,...,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region
3,907,Premium Sliced Bacon,106,12,20.0,2254091,138,10,5,14,...,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region
6,4913,Table Water Crackers,78,19,4.4,894221,138,23,5,13,...,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region
10,7987,Hazelnut Spread with Cocoa,88,13,12.8,1592314,138,5,0,9,...,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region

In [5]:
df_cust.tail()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_time_of_day,...,surname,gender,state,age,date_joined,num_of_dependants,family_status,income,_merge,region
32404841,49235,Organic Half & Half,53,16,1.8,2939801,27382,3,3,8,...,Allison,Female,Vermont,68,11/25/2019,3,married,37867,both,northeast_region
32404842,49235,Organic Half & Half,53,16,1.8,698928,27382,4,3,7,...,Allison,Female,Vermont,68,11/25/2019,3,married,37867,both,northeast_region
32404843,49235,Organic Half & Half,53,16,1.8,3310701,27382,5,3,9,...,Allison,Female,Vermont,68,11/25/2019,3,married,37867,both,northeast_region
32404849,49235,Organic Half & Half,53,16,1.8,952054,56454,2,3,9,...,Velazquez,Male,Washington,21,2/16/2019,3,living with parents and siblings,27361,both,pacific_region
32404850,49235,Organic Half & Half,53,16,1.8,1189204,56454,3,1,19,...,Velazquez,Male,Washington,21,2/16/2019,3,living with parents and siblings,27361,both,pacific_region

In [6]:
# Data types

df_cust.dtypes

product_id                    int64
product_name                 object
aisle_id                      int64
department_id                 int64
prices                      float64
order_id                      int64
user_id                      object
order_number                  int64
orders_day_of_week            int64
order_time_of_day             int64
days_since_prior_order      float64
first_time_order               bool
add_to_cart_order             int64
reordered                     int64
price_range_loc              object
busiest_day                  object
busiest_days                 object
busiest_period_of_day        object
max_order                     int64
loyalty_flag                 object
mean_prices                 float64
spending_flag                object
median_days_prior_order     float64
frequency_flag               object
first_name                   object
surname                      object
gender                       object
state                        object
age                           int64
date_joined                  object
num_of_dependants             int64
family_status                object
income                        int64
_merge                     category
region                       object
dtype: object

In [7]:
df_cust.shape

(9721098, 35)

In [8]:
df_cust.describe()

,product_id,aisle_id,department_id,prices,order_id,order_number,orders_day_of_week,order_time_of_day,days_since_prior_order,add_to_cart_order,reordered,max_order,mean_prices,median_days_prior_order,age,num_of_dependants,income
count,9.721098e+06,9.721098e+06,9.721098e+06,9.721098e+06,9.721098e+06,9.721098e+06,9.721098e+06,9.721098e+06,9.098421e+06,9.721098e+06,9.721098e+06,9.721098e+06,9.721098e+06,9.721096e+06,9.721098e+06,9.721098e+06,9.721098e+06
mean,2.559919e+04,7.118637e+01,9.916921e+00,1.196327e+01,1.710382e+06,1.714078e+01,2.738444e+00,1.342467e+01,1.110574e+01,8.352290e+00,5.895577e-01,3.304783e+01,1.198767e+01,1.039815e+01,4.946312e+01,1.501945e+00,9.944555e+04
std,1.408325e+04,3.821429e+01,6.281223e+00,4.923865e+02,9.874306e+05,1.753615e+01,2.089993e+00,4.244412e+00,8.779462e+00,7.126665e+00,4.919141e-01,2.515526e+01,8.257014e+01,7.132534e+00,1.848655e+01,1.118746e+00,4.308561e+04
min,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.800000e+01,0.000000e+00,2.590300e+04
25%,1.354400e+04,3.100000e+01,4.000000e+00,4.200000e+00,8.555800e+05,5.000000e+00,1.000000e+00,1.000000e+01,5.000000e+00,3.000000e+00,0.000000e+00,1.300000e+01,7.386957e+00,6.000000e+00,3.300000e+01,1.000000e+00,6.699100e+04
50%,2.530900e+04,8.300000e+01,9.000000e+00,7.400000e+00,1.710702e+06,1.100000e+01,3.000000e+00,1.300000e+01,8.000000e+00,6.000000e+00,1.000000e+00,2.600000e+01,7.824688e+00,8.000000e+00,4.900000e+01,2.000000e+00,9.663000e+04
75%,3.794700e+04,1.070000e+02,1.600000e+01,1.130000e+01,2.565431e+06,2.400000e+01,5.000000e+00,1.600000e+01,1.500000e+01,1.100000e+01,1.000000e+00,4.700000e+01,8.253789e+00,1.300000e+01,6.500000e+01,3.000000e+00,1.279160e+05
max,4.968800e+04,1.340000e+02,2.100000e+01,9.999900e+04,3.421083e+06,9.900000e+01,6.000000e+00,2.300000e+01,3.000000e+01,1.430000e+02,1.000000e+00,9.900000e+01,1.500694e+04,3.000000e+01,8.100000e+01,3.000000e+00,5.939010e+05

## 2.  Create an exclusion flag

In [9]:
df_cust.loc[df_cust['order_number'] < 5, 'activity_flag'] = 'low activity'

In [12]:
df_cust.loc[df_cust['order_number'] >= 5, 'activity_flag'] = 'active'

In [10]:
pd.options.display.max_rows = None

In [23]:
df_cust.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_time_of_day,...,gender,state,age,date_joined,num_of_dependants,family_status,income,_merge,region,activity_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
2,907,Premium Sliced Bacon,106,12,20.0,3160996,138,1,5,13,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,low activity
3,907,Premium Sliced Bacon,106,12,20.0,2254091,138,10,5,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
6,4913,Table Water Crackers,78,19,4.4,894221,138,23,5,13,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
10,7987,Hazelnut Spread with Cocoa,88,13,12.8,1592314,138,5,0,9,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
12,8048,Packaged Grape Tomatoes,32,4,11.4,1421595,138,3,2,9,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,low activity
13,10473,Half And Half Cream,53,16,7.0,3160996,138,1,5,13,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,low activity
19,10473,Half And Half Cream,53,16,7.0,2823056,138,8,6,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
21,10473,Half And Half Cream,53,16,7.0,2526903,138,14,0,15,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
22,10473,Half And Half Cream,53,16,7.0,1593782,138,15,6,11,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
23,10473,Half And Half Cream,53,16,7.0,307762,138,16,0,11,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
28,10473,Half And Half Cream,53,16,7.0,703615,138,25,3,11,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
31,12341,Hass Avocados,32,4,9.1,3160996,138,1,5,13,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,low activity
42,14032,Tortilla Chips,107,19,3.9,505689,138,9,6,12,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
50,16974,Sea Salt Brown Rice Crackers,107,19,5.1,3160996,138,1,5,13,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,low activity
56,16974,Sea Salt Brown Rice Crackers,107,19,5.1,28517,138,13,6,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
58,16974,Sea Salt Brown Rice Crackers,107,19,5.1,307762,138,16,0,11,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
60,21292,Rainbow Bell Peppers,32,4,11.7,930730,138,2,0,12,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,low activity
64,21573,Roasted Pine Nut Hummus,67,20,1.4,1986630,138,7,0,12,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
65,21573,Roasted Pine Nut Hummus,67,20,1.4,28517,138,13,6,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
70,21769,Chunky Guacamole,67,20,13.6,307762,138,16,0,11,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
71,21903,Organic Baby Spinach,123,4,8.2,3160996,138,1,5,13,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,low activity
79,22046,Frozen Whole Strawberries,116,1,14.0,3139998,138,28,6,11,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
85,22469,Nacho Cheese Flavored Tortilla Chips,107,19,5.1,2526903,138,14,0,15,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
87,26152,Granulated Sugar,17,13,12.7,1421595,138,3,2,9,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,low activity
89,26491,Full Size Milk Chocolate Bar With Almonds,45,19,2.0,2254091,138,10,5,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
93,28413,Bunny-Luv Organic Carrots,83,4,4.5,1986630,138,7,0,12,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
103,31860,Foil Sheets,85,17,11.7,1593782,138,15,6,11,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
104,32478,Reduced Fat 2% Milk,84,16,13.9,2206168,138,27,3,18,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
107,33147,Organic Crimini Mushrooms,83,4,9.8,2526903,138,14,0,15,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
109,33147,Organic Crimini Mushrooms,83,4,9.8,2226790,138,26,5,12,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
114,37317,Wonderful 100% Pomegranate Juice,31,7,8.7,28517,138,13,6,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
115,37687,Organic Spring Mix,123,4,5.5,960220,138,17,5,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
117,40199,Chocolate Chip Cookies,61,19,5.0,1069065,138,31,2,7,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
119,42282,Bag of Jumbo Yellow Onions,32,4,1.6,1421595,138,3,2,9,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,low activity
121,42475,Unsalted Butter Quarters,36,16,2.6,505689,138,9,6,12,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
122,42475,Unsalted Butter Quarters,36,16,2.6,2254091,138,10,5,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
123,42475,Unsalted Butter Quarters,36,16,2.6,960220,138,17,5,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
124,42475,Unsalted Butter Quarters,36,16,2.6,1972635,138,20,6,20,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
134,46802,Pineapple Chunks,116,1,1.8,2526903,138,14,0,15,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
135,46802,Pineapple Chunks,116,1,1.8,1593782,138,15,6,11,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
141,46802,Pineapple Chunks,116,1,1.8,2226790,138,26,5,12,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
143,46802,Pineapple Chunks,116,1,1.8,1854193,138,29,0,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
144,46802,Pineapple Chunks,116,1,1.8,1069065,138,31,2,7,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
148,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
149,196,Soda,77,7,9.0,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
152,587,Air Effects Gain Island Fresh,101,17,3.1,389851,709,2,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
153,955,Cheddar Chex Mix,125,19,3.9,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
155,1519,Thin Pizza Crust,105,13,5.2,389851,709,2,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
156,1582,Turkey Pepperoni Slices,96,20,4.7,389851,709,2,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
161,3796,Ranchero Braised Beef,38,1,9.3,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
164,4461,Organic Raw Unfiltered Apple Cider Vinegar,19,13,14.3,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
165,4514,Reduced Fat Colby-Jack Cheese Sticks,21,16,6.2,1284746,709,1,1,19,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
166,4700,100% Whole Wheat 8 Hot Dog Rolls,43,3,7.5,1284746,709,1,1,19,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
167,4852,NOTICeables French Lavender & Riviera Nights S...,101,17,1.6,1284746,709,1,1,19,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
171,5636,Vanilla and Chocolate Low Fat Ice Cream Sandwi...,37,1,11.0,1331431,709,3,6,15,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
172,5737,Reduced Sugar Tomato Ketchup,72,13,11.6,1284746,709,1,1,19,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
174,6046,Boneless Skinless Chicken Breast,35,12,11.9,1284746,709,1,1,19,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
184,7606,Greek 100 Protein Vanilla Fat Free Yogurt,120,16,12.2,389851,709,2,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
188,8274,Fresh Cut Cauliflower & Broccoli Steam in Bag,123,4,10.1,389851,709,2,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
189,8292,100 Calorie Healthy Pop Butter Microwave Pop Corn,23,19,6.2,2322397,709,5,1,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,active
190,8587,Family Pack Bean & Cheese Burritos,38,1,1.7,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
192,9176,Sesame Stir Fry with Chicken,38,1,14.5,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
195,9547,Turkey Franks,106,12,8.1,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
197,10279,Lunchables Pepperoni Pizza,13,20,7.0,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
198,10279,Lunchables Pepperoni Pizza,13,20,7.0,2322397,709,5,1,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,active
202,11993,Sharp Cheddar Cheese Slices,21,16,8.5,389851,709,2,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
212,13400,"Corn Dogs, 100% Beef",38,1,6.7,2322397,709,5,1,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,active
214,14118,Pretzel Bread Grilled Chicken with Jalapeno Ch...,38,1,9.3,2322397,709,5,1,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,active
218,14634,Original Spread,36,16,6.0,1284746,709,1,1,19,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
219,14783,Chocolate Crunch Rice Cakes,78,19,3.2,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
221,15599,Naturally Hickory Smoked Thick Cut Bacon,106,12,16.7,1331431,709,3,6,15,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
222,15925,Macaroni and Cheese,38,1,1.8,1331431,709,3,6,15,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
223,16380,Stevia Sweetener,97,13,2.5,1284746,709,1,1,19,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
224,16797,Strawberries,24,4,1.3,1284746,709,1,1,19,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
225,16797,Strawberries,24,4,1.3,2322397,709,5,1,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,active
230,18686,Cookies & Cream Ice Cream Bars,37,1,13.4,1284746,709,1,1,19,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
239,21760,Greek 100 Calories Blended Strawberry Cheeseca...,120,16,12.5,389851,709,2,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
246,22340,Fig Newtons,61,19,7.0,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
249,22730,Singles 1% Lowfat Cottage Cheese,108,16,2.2,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
252,23431,Peppermint Mocha Liquid Coffee Creamer,53,16,3.7,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
266,25347,Greek 100 Calories Strawberry Banana Fat Free ...,120,16,12.3,389851,709,2,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
277,27388,Lunchable Extra Cheesy Pizza,96,20,6.9,389851,709,2,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
278,27388,Lunchable Extra Cheesy Pizza,96,20,6.9,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
279,27388,Lunchable Extra Cheesy Pizza,96,20,6.9,2322397,709,5,1,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,active
286,29082,Waffle Fries French Fried Potatoes,129,1,14.5,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
287,29309,Spaghetti with Meat Sauce Pasta Meal,38,1,6.6,1331431,709,3,6,15,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
289,30721,No Beans Chili,59,15,8.1,1331431,709,3,6,15,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
292,31573,Whole Grain Brown Ready Rice,4,9,7.5,1284746,709,1,1,19,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
300,35660,Keurig Daybreak Morning Blend Coffee K Cups,26,7,5.9,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
303,36046,Greek 100 Calories Mixed Berry Yogurt,120,16,3.5,1331431,709,3,6,15,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
304,36046,Greek 100 Calories Mixed Berry Yogurt,120,16,3.5,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
309,37089,Caribou Blend Coffee K-Cups,26,7,11.1,2322397,709,5,1,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,active
312,39844,Mini Sweet Peppers,83,4,1.7,1331431,709,3,6,15,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
316,40415,Fajitas Seasoning Mix,5,13,11.7,1331431,709,3,6,15,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
323,43508,Breaded Mozzarella Sticks,129,1,8.2,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
326,43611,Greek 100 Calories Blueberry Fat Free Yogurt,120,16,11.9,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
327,43611,Greek 100 Calories Blueberry Fat Free Yogurt,120,16,11.9,2322397,709,5,1,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,active
329,44487,Lightly Salted Rice Cakes,78,19,3.5,1331431,709,3,6,15,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity
330,45287,Kosher Dill Sandwich Slices,110,13,11.6,147387,709,4,0,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,low activity

In [24]:
df_cust['activity_flag'].value_counts(dropna = False)

active          7323504
low activity    2397594
Name: activity_flag, dtype: int64

In [22]:
# Export modified small_cop_sample dataframe

df_cust.to_pickle(os.path.join(path, '02_Data','Prepared_Data', 'small_cop_sample.pkl'))

  
## 3. Exclude low activity customers from the dataframe

In [32]:
# selecting rows based on 'active' condition

name = ['active']

df_cust2 = df_cust.loc[df_cust['activity_flag'].isin(name)]

In [34]:
df_cust2.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_time_of_day,...,gender,state,age,date_joined,num_of_dependants,family_status,income,_merge,region,activity_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
3,907,Premium Sliced Bacon,106,12,20.0,2254091,138,10,5,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
6,4913,Table Water Crackers,78,19,4.4,894221,138,23,5,13,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
10,7987,Hazelnut Spread with Cocoa,88,13,12.8,1592314,138,5,0,9,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
19,10473,Half And Half Cream,53,16,7.0,2823056,138,8,6,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
21,10473,Half And Half Cream,53,16,7.0,2526903,138,14,0,15,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
22,10473,Half And Half Cream,53,16,7.0,1593782,138,15,6,11,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
23,10473,Half And Half Cream,53,16,7.0,307762,138,16,0,11,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
28,10473,Half And Half Cream,53,16,7.0,703615,138,25,3,11,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
42,14032,Tortilla Chips,107,19,3.9,505689,138,9,6,12,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
56,16974,Sea Salt Brown Rice Crackers,107,19,5.1,28517,138,13,6,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
58,16974,Sea Salt Brown Rice Crackers,107,19,5.1,307762,138,16,0,11,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
64,21573,Roasted Pine Nut Hummus,67,20,1.4,1986630,138,7,0,12,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
65,21573,Roasted Pine Nut Hummus,67,20,1.4,28517,138,13,6,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
70,21769,Chunky Guacamole,67,20,13.6,307762,138,16,0,11,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
79,22046,Frozen Whole Strawberries,116,1,14.0,3139998,138,28,6,11,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
85,22469,Nacho Cheese Flavored Tortilla Chips,107,19,5.1,2526903,138,14,0,15,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
89,26491,Full Size Milk Chocolate Bar With Almonds,45,19,2.0,2254091,138,10,5,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
93,28413,Bunny-Luv Organic Carrots,83,4,4.5,1986630,138,7,0,12,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
103,31860,Foil Sheets,85,17,11.7,1593782,138,15,6,11,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
104,32478,Reduced Fat 2% Milk,84,16,13.9,2206168,138,27,3,18,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
107,33147,Organic Crimini Mushrooms,83,4,9.8,2526903,138,14,0,15,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
109,33147,Organic Crimini Mushrooms,83,4,9.8,2226790,138,26,5,12,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
114,37317,Wonderful 100% Pomegranate Juice,31,7,8.7,28517,138,13,6,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
115,37687,Organic Spring Mix,123,4,5.5,960220,138,17,5,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
117,40199,Chocolate Chip Cookies,61,19,5.0,1069065,138,31,2,7,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
121,42475,Unsalted Butter Quarters,36,16,2.6,505689,138,9,6,12,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
122,42475,Unsalted Butter Quarters,36,16,2.6,2254091,138,10,5,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
123,42475,Unsalted Butter Quarters,36,16,2.6,960220,138,17,5,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
124,42475,Unsalted Butter Quarters,36,16,2.6,1972635,138,20,6,20,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
134,46802,Pineapple Chunks,116,1,1.8,2526903,138,14,0,15,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
135,46802,Pineapple Chunks,116,1,1.8,1593782,138,15,6,11,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
141,46802,Pineapple Chunks,116,1,1.8,2226790,138,26,5,12,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
143,46802,Pineapple Chunks,116,1,1.8,1854193,138,29,0,14,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
144,46802,Pineapple Chunks,116,1,1.8,1069065,138,31,2,7,...,Male,Minnesota,81,8/1/2019,1,married,49620,both,midwest_region,active
189,8292,100 Calorie Healthy Pop Butter Microwave Pop Corn,23,19,6.2,2322397,709,5,1,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,active
198,10279,Lunchables Pepperoni Pizza,13,20,7.0,2322397,709,5,1,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,active
212,13400,"Corn Dogs, 100% Beef",38,1,6.7,2322397,709,5,1,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,active
214,14118,Pretzel Bread Grilled Chicken with Jalapeno Ch...,38,1,9.3,2322397,709,5,1,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,active
225,16797,Strawberries,24,4,1.3,2322397,709,5,1,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,active
279,27388,Lunchable Extra Cheesy Pizza,96,20,6.9,2322397,709,5,1,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,active
309,37089,Caribou Blend Coffee K-Cups,26,7,11.1,2322397,709,5,1,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,active
327,43611,Greek 100 Calories Blueberry Fat Free Yogurt,120,16,11.9,2322397,709,5,1,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,active
334,48440,Pepperoni Pizza Rolls,129,1,14.2,2322397,709,5,1,21,...,Female,Vermont,66,6/16/2018,2,married,158302,both,northeast_region,active
398,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
403,4724,Broccoli Florettes,32,4,7.8,677426,777,9,4,10,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
409,4913,Table Water Crackers,78,19,4.4,1701441,777,16,1,7,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
412,8048,Packaged Grape Tomatoes,32,4,11.4,3379288,777,20,6,8,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
420,12341,Hass Avocados,32,4,9.1,348001,777,6,4,7,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
422,12341,Hass Avocados,32,4,9.1,2416574,777,14,0,13,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
425,12341,Hass Avocados,32,4,9.1,2019394,777,22,0,17,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
432,13176,Bag of Organic Bananas,24,4,10.3,348001,777,6,4,7,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
433,13176,Bag of Organic Bananas,24,4,10.3,2785250,777,8,2,16,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
435,13176,Bag of Organic Bananas,24,4,10.3,941257,777,11,6,20,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
436,13176,Bag of Organic Bananas,24,4,10.3,3313711,777,12,3,22,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
440,13176,Bag of Organic Bananas,24,4,10.3,2046360,777,21,5,9,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
444,16797,Strawberries,24,4,1.3,677426,777,9,4,10,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
448,16797,Strawberries,24,4,1.3,2945376,777,13,2,22,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
450,16797,Strawberries,24,4,1.3,1701441,777,16,1,7,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
453,16797,Strawberries,24,4,1.3,3379288,777,20,6,8,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
454,16797,Strawberries,24,4,1.3,2046360,777,21,5,9,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
456,16797,Strawberries,24,4,1.3,2842231,777,24,5,11,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
461,17122,Honeycrisp Apples,24,4,14.0,2823923,777,18,2,11,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
466,17313,Hass Avocado Variety,24,4,7.9,1701441,777,16,1,7,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
472,20955,Cereal,121,14,10.0,941257,777,11,6,20,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
476,21288,Blackberries,24,4,8.3,3313711,777,12,3,22,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
477,21288,Blackberries,24,4,8.3,2945376,777,13,2,22,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
479,21288,Blackberries,24,4,8.3,2516805,777,19,6,9,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
480,21288,Blackberries,24,4,8.3,3379288,777,20,6,8,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
483,21903,Organic Baby Spinach,123,4,8.2,2516805,777,19,6,9,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
484,29223,Golden Pineapple,24,4,8.9,2019394,777,22,0,17,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
486,29223,Golden Pineapple,24,4,8.9,2084145,777,25,3,9,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
489,30827,Seedless Cucumbers,32,4,7.2,2785250,777,8,2,16,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
492,30827,Seedless Cucumbers,32,4,7.2,3119188,777,17,5,1,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
493,30827,Seedless Cucumbers,32,4,7.2,2019394,777,22,0,17,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
499,35951,Organic Unsweetened Almond Milk,91,16,1.3,2516805,777,19,6,9,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
500,35951,Organic Unsweetened Almond Milk,91,16,1.3,2019394,777,22,0,17,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
502,40199,Chocolate Chip Cookies,61,19,5.0,1743519,777,23,3,8,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
504,43352,Raspberries,32,4,1.4,3379288,777,20,6,8,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
505,43352,Raspberries,32,4,1.4,2019394,777,22,0,17,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
506,43352,Raspberries,32,4,1.4,2842231,777,24,5,11,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
507,43352,Raspberries,32,4,1.4,1339393,777,26,1,10,...,Female,Hawaii,51,1/4/2019,2,married,57797,both,pacific_region,active
524,13176,Bag of Organic Bananas,24,4,10.3,156520,825,6,0,22,...,Male,District of Columbia,20,5/8/2019,3,living with parents and siblings,34171,both,south_region,active
529,30633,Veggie Cheese & Pretzel Snack Pac Prepacked,50,19,2.7,2421542,825,5,0,22,...,Male,District of Columbia,20,5/8/2019,3,living with parents and siblings,34171,both,south_region,active
532,31651,Extra Fancy Unsalted Mixed Nuts,117,19,3.4,2015258,825,9,1,16,...,Male,District of Columbia,20,5/8/2019,3,living with parents and siblings,34171,both,south_region,active
536,40939,Drinking Water,115,7,1.6,2724496,825,7,5,14,...,Male,District of Columbia,20,5/8/2019,3,living with parents and siblings,34171,both,south_region,active
537,40939,Drinking Water,115,7,1.6,889004,825,8,2,18,...,Male,District of Columbia,20,5/8/2019,3,living with parents and siblings,34171,both,south_region,active
542,47402,Fuji Apples,24,4,7.1,156520,825,6,0,22,...,Male,District of Columbia,20,5/8/2019,3,living with parents and siblings,34171,both,south_region,active
543,47402,Fuji Apples,24,4,7.1,2724496,825,7,5,14,...,Male,District of Columbia,20,5/8/2019,3,living with parents and siblings,34171,both,south_region,active
550,14032,Tortilla Chips,107,19,3.9,3297166,910,10,2,10,...,Female,Tennessee,65,7/25/2019,0,divorced/widowed,44856,both,south_region,active
552,21769,Chunky Guacamole,67,20,13.6,1782479,910,11,3,11,...,Female,Tennessee,65,7/25/2019,0,divorced/widowed,44856,both,south_region,active
553,21873,Fruit Snacks,50,19,2.1,1315954,910,9,3,12,...,Female,Tennessee,65,7/25/2019,0,divorced/widowed,44856,both,south_region,active
560,46061,Popcorn,23,19,5.3,1093241,910,8,3,11,...,Female,Tennessee,65,7/25/2019,0,divorced/widowed,44856,both,south_region,active
561,46061,Popcorn,23,19,5.3,1315954,910,9,3,12,...,Female,Tennessee,65,7/25/2019,0,divorced/widowed,44856,both,south_region,active
564,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,...,Male,Oregon,72,3/30/2018,1,married,153843,both,pacific_region,active
565,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,...,Male,Oregon,72,3/30/2018,1,married,153843,both,pacific_region,active
568,6901,Raisin Bran,121,14,2.9,2889030,1052,9,3,20,...,Male,Oregon,72,3/30/2018,1,married,153843,both,pacific_region,active
571,8514,Egg Whites,86,16,12.7,2239544,1052,7,6,10,...,Male,Oregon,72,3/30/2018,1,married,153843,both,pacific_region,active
574,11365,Leaf Spinach,32,4,9.8,2072025,1052,5,1,8,...,Male,Oregon,72,3/30/2018,1,married,153843,both,pacific_region,active
581,14364,Paneer,21,16,13.9,1219437,1052,6,5,23,...,Male,Oregon,72,3/30/2018,1,married,153843,both,pacific_region,active

## 4. Export sample containing only active customers

In [35]:
df_cust2.to_pickle(os.path.join(path, '02_Data','Prepared_Data', 'cop_sample_active.pkl'))